version: '3'

services:
  front:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:3000
    env_file:
      - .env
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    tty: true
    stdin_open: true